Sync up release docs with react router
remix-run/react-router pull request #10065
Opened 2023-02-07 21:43 UTC by brophdawg11

2023-02-07 22:14 UTC, MichaelDeBoey requested changes

2023-02-07 22:14 UTC, MichaelDeBoey commented on DEVELOPMENT.md
> +  - merge the `release-*` branch into `dev` and push it up to Github
```suggestion
  - merge the `release-*` branch into `main` and push it up to GitHub
  - merge the `release-*` branch into `dev` and push it up to GitHub
```

2023-02-07 22:14 UTC, MichaelDeBoey requested changes

2023-02-07 22:14 UTC, MichaelDeBoey commented on DEVELOPMENT.md
> +  - merge the `release-*` branch into `dev` and push it up to Github
```suggestion
  - merge the `release-*` branch into `main` and push it up to GitHub
  - merge the `release-*` branch into `dev` and push it up to GitHub
```

2023-02-08 15:10 UTC, chaance approved these changes

2023-02-09 17:41 UTC, merged