Make resolve.conditions work with Vite v6
remix-run/react-router pull request #12644
Opened 2024-12-26 17:01 UTC by silvenon

Configuring `resolve.conditions` in Vite v6 has changed: https://vite.dev/guide/migration.html#default-value-for-resolve-conditions

The configured conditions are no longer added to the default values, they now _replace_ the defaults. This was causing problems with resolving packages like `@prisma/client` during SSR.

This fix adds the missing default values if they exist, otherwise it preserves the previous behavior in order to (hopefully) maintain compatibility with Vite v5.

Fixes #12610.

2025-01-04 14:12 UTC, tigerabrodi requested changes
I'm wondering if we should add tests?

This is critical code handling module resolution, important part how deps get loaded in the application

subtle bugs ruin it for many and cause hours of debugging 🤷 

we should cover this with tests imo

2025-01-04 14:12 UTC, tigerabrodi commented on packages/react-router-dev/vite/plugin.ts
> +                  : ["development", ...viteServerConditions],
I would add a comment and explain why we need this, and link to: https://vite.dev/guide/migration#default-value-for-resolve-conditions

Something like:

```
// Vite 6 no longer adds default conditions internally.
// We need to explicitly include them to ensure proper module resolution
// especially for packages that rely on specific conditions like @prisma/client
// see {link}
```

Maybe it's just me, but this code is quite critical as it handles module resolution, which is a critical part of how dependencies get loaded in the application

i would prefer being very clear here

2025-01-04 14:12 UTC, tigerabrodi commented on packages/react-router-dev/vite/plugin.ts
> +            : [];
We could make this more type safe by specifying the literal types accepted here.

```js
type DevProdCondition = 'development' | 'production';
type BaseCondition = 'module' | DevProdCondition;

type ClientCondition = BaseCondition | 'browser';
type ServerCondition = BaseCondition | 'node' | 'workerd' | 'worker';
```

You could then use this as `ClientCondition[]` or `ServerCondition[]`.

Reading the vite docs and seeing what we have here, I think this should be fine, also helps make sure we don't mistype anything.

2025-01-04 14:16 UTC, tigerabrodi commented
i think we should add a test here @silvenon 

if rr team had a test for this config in the first place, it would've been caught before shipping to production, im not entirely sure what the conventions here are etc.

i was playing around with code quickly, but the test case below should've caught the issue

i imagine it looking like:

```js
import { describe, it, expect, beforeEach } from 'vitest';

type DevProdCondition = 'development' | 'production';
type BaseCondition = 'module' | DevProdCondition;
type ServerCondition = BaseCondition | 'node' | 'workerd' | 'worker';

interface ViteConfig {
 ssr?: {
   resolve?: {
     conditions?: string[];
   }
 }
}

interface ConditionsConfig {
 vite: {
   defaultServerConditions?: string[];
 };
 userConfig?: ViteConfig;
 command: 'build' | 'serve';
}

function getServerConditions({
 vite,
 userConfig,
 command
}: ConditionsConfig): string[] {
 // Check user config first
 if (userConfig?.ssr?.resolve?.conditions !== undefined) {
   return userConfig.ssr.resolve.conditions;
 }

 // Get Vite defaults or empty array if old Vite version
 const defaultConditions = "defaultServerConditions" in vite
   ? Array.from(vite.defaultServerConditions)
   : [];

 // Add development in dev mode
 return command === 'build' 
   ? defaultConditions
   : ['development', ...defaultConditions];
}

describe('Server Conditions', () => {
 let mockVite: ConditionsConfig['vite'];
 let mockUserConfig: ViteConfig;
 
 beforeEach(() => {
   // Reset mocks before each test
   mockVite = {
     defaultServerConditions: ['module', 'node']
   };
   mockUserConfig = {};
 });

// a case like this would've caught the issue ensuring conditions isn't empty
 it('should use Vite default server conditions in build mode', () => {
   const conditions = getServerConditions({
     vite: mockVite,
     userConfig: mockUserConfig,
     command: 'build'
   });
   
   expect(conditions).toEqual(['module', 'node']);
 });
});
```

2025-01-04 18:30 UTC, silvenon commented on packages/react-router-dev/vite/plugin.ts
> +                  : ["development", ...viteServerConditions],
Good idea, I added some comments.

2025-01-04 18:30 UTC, silvenon commented on packages/react-router-dev/vite/plugin.ts
> +            : [];
I don't see the benefit of coercing unknown strings to known strings.

2025-01-04 18:34 UTC, silvenon commented
> i think we should add a test here

I'd like to add something, but I'd like to wait for some team feedback first, I don't really know how to test this, but thanks for your suggestion. TBH I don't know why `"development"` condition is even being added at all. I thought that Vite by default resolves to `"development"` condition during development mode and to `"production"` condition during build. Both in Vite v5 and v6.

2025-01-05 22:16 UTC, markdalgleish commented on packages/react-router-dev/vite/cloudflare-dev-proxy.ts
> +        userConfig.ssr?.resolve?.externalConditions ??
Merging the external conditions from the user config is new behaviour that should be considered separately from this Vite 6 fix. Can we roll this back here and in the other two places?

2025-01-05 22:29 UTC, markdalgleish commented on packages/react-router-dev/vite/cloudflare-dev-proxy.ts
> +import { preloadViteEsm, importViteEsmSync } from "./import-vite-esm-sync";
This has changed in the `dev` branch.

```suggestion
import { preloadVite, getVite } from "./vite";
```

2025-01-05 22:32 UTC, silvenon commented on packages/react-router-dev/vite/cloudflare-dev-proxy.ts
> +        userConfig.ssr?.resolve?.externalConditions ??
Oops, indeed. Rolled back.

2025-01-05 22:43 UTC, silvenon commented on packages/react-router-dev/vite/cloudflare-dev-proxy.ts
> +import { preloadViteEsm, importViteEsmSync } from "./import-vite-esm-sync";
Updated.

2025-01-05 22:47 UTC, silvenon commented
@markdalgleish done. Do you know the reason for adding the `"development"` condition in the first place? Is it for virtual modules?

2025-01-05 22:52 UTC, markdalgleish commented
@silvenon It was added in this PR: https://github.com/remix-run/react-router/pull/12269 — but this change was later rolled back. Looks like the condition was accidentally left in, but as you pointed out, it might not have been needed in the first place. We could look at removing this in a separate PR.

2025-01-05 23:01 UTC, markdalgleish commented on .changeset/beige-ants-pay.md
> +Fix issue with fetcher data cleanup in the data layer on fetcher unmount
Your PR is targeting `main` instead of `dev`, so the merge has added a bunch of extra changes like this. Could you update the base branch for this PR?

2025-01-05 23:48 UTC, silvenon commented on .changeset/beige-ants-pay.md
> +Fix issue with fetcher data cleanup in the data layer on fetcher unmount
Oops, initially I thought I was supposed to base my PRs off of `main`, but now I know. Changed base.

2025-01-05 23:51 UTC, silvenon commented on contributors.yml
> +- bravo-kernel
Seems like `main` and `dev` are not entirely in sync, by basing this off of `main` I'm merging this name into contributors. Should I remove it?

2025-01-05 23:52 UTC, markdalgleish commented on contributors.yml
> +- bravo-kernel
This change was left in.

2025-01-05 23:53 UTC, markdalgleish commented on docs/explanation/special-files.md
> +    // Abort the streaming render pass after 11 seconds so to allow the rejected
This was accidentally included too.

2025-01-05 23:53 UTC, markdalgleish commented on packages/react-router-dev/vite/plugin.ts
> +            ? Array.from(vite.defaultClientConditions)
Why is `Array.from` used here?

2025-01-05 23:55 UTC, silvenon commented on packages/react-router-dev/vite/plugin.ts
> +            ? Array.from(vite.defaultClientConditions)
To satisfy TypeScript, I can also do `[...vite.defaultClientConditions]`

2025-01-06 00:02 UTC, markdalgleish commented on packages/react-router-dev/vite/plugin.ts
> +            ? Array.from(vite.defaultClientConditions)
Could do `...vite.defaultClientConditions ?? []` (and similar in all other cases) to inline it?

2025-01-06 00:03 UTC, markdalgleish commented on contributors.yml
> +- bravo-kernel
Yep, this should be removed, and the comment change too.

Sorry, I missed this comment when replying earlier.

2025-01-06 00:08 UTC, silvenon commented on packages/react-router-dev/vite/plugin.ts
> +            ? Array.from(vite.defaultClientConditions)
I've done spreading instead, shorter.

2025-01-06 00:10 UTC, silvenon commented
I don't like rebasing, but if there's one circumstance where it's appropriate, it's when I literally based my branch off the wrong one. Here, everything clean now.

2025-01-06 00:26 UTC, silvenon commented on packages/react-router-dev/vite/plugin.ts
> +            ? Array.from(vite.defaultClientConditions)
> Could do `...vite.defaultClientConditions ?? []` (and similar in all other cases) to inline it?

Ah, sorry, I didn't see this. I pushed the change now, let me know if this is what you meant.

2025-01-06 00:52 UTC, markdalgleish approved these changes
I've just pushed a couple of minor tweaks to finish this off.

Thanks for your work on this 🙏

2025-01-06 00:53 UTC, merged

2025-01-06 01:12 UTC, silvenon commented
You're welcome, I'm very glad this got merged, thanks for your reviews!