fix(react-router-dom): fix submitter serialization
remix-run/react-router pull request #9865
Opened 2023-01-10 01:11 UTC by jenseng

This is the RR port of https://github.com/remix-run/remix/pull/4474

Bring `<Form>` submissions in line with the spec with respect to how and where form submitters are serialized within the data set. We accomplish this by temporarily tweaking the form during submission to get the right entries.

Problems fixed:
1. Serialize submitters in tree order (i.e. where they appear in the DOM)
2. Serialize Image Button submitter correctly (i.e. separate x and y coordinate entries, rather than a single empty entry)
3. Stop sending multiple entries in older WebKit

Notes: requires a couple more jsdom polyfills in order to test it, but we should be able to upgrade and remove those soon 🤞

References: https://github.com/remix-run/remix/issues/4342
Spec: https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#constructing-form-data-set

2023-01-12 17:25 UTC, jenseng commented
Seeing if I can get the ball rolling on [adding submitter to the FormData constructor in the spec](https://github.com/whatwg/xhr/pull/366), then evergreen browsers could support this natively and we'd only need to polyfill for older ones 🤞

2023-01-24 22:35 UTC, brophdawg11 commented
ok talked to Michael and Ryan and gonna aim to get this approach merged - I'll try to take a deeper look through it this week 👍

2023-01-24 22:43 UTC, jenseng commented
Nice! Looks like momentum is building on getting the FormData constructor updated to include the submitter ... I already have basic implementations in Blink/Firefox/WebKit/jsdom, and so far the Blink/Firefox implementors have expressed interest 🥳 

Assuming that's the direction things go, I wonder if I should extract this into a simple/standalone polyfill that Remix could use? Then the actual Remix change is just a couple lines, wdyt?

2023-01-24 22:50 UTC, brophdawg11 commented
Awesome news!  Yeah personally I'd love to _not_ have to have Remix/RR worry about this at all and let the browser handle it if supported, and let users polyfill otherwise (if they care about serialization order).  Is that what you're envisioning?

2023-01-24 23:03 UTC, jenseng commented
This patch (and an equivalent standalone polyfill) fixes more than just the order, but that could be a good starting point, e.g.

```javascript
formData = new FormData(form, target);

// For older browsers that don't support the FormData constructor submitter parameter,
// be sure to set a value. To more robustly support old browsers in your Remix app,
// consider using the `formdata-submitter-polyfill` package
if (FormData.constructor.length === 1 && target.name && target.type === "submit") {
  formData.append(target.name, target.value);
}
```

The nice thing about rolling the polyfill/fix into RR is it also 1. fixes the values for image buttons (i.e. you get x/y coordinates) and 2. it fixes the double-submitter bug in old Safari

2023-01-27 00:51 UTC, MichaelDeBoey requested changes
I think we can remove both polyfills & update `jsdom` version as https://github.com/jsdom/jsdom/pull/3480 & https://github.com/jsdom/jsdom/pull/3484 are both merged & released

2023-01-27 01:08 UTC, jenseng commented
The polyfills are no longer needed when using `jsdom@21.1.0`, but [jest still requires `jsdom@20.x`](https://github.com/facebook/jest/blob/main/packages/jest-environment-jsdom/package.json#L27) ... I'll see if I can move the needle there

2023-01-30 16:23 UTC, jenseng commented
FormData `submitter` has [landed in the spec](https://xhr.spec.whatwg.org/#interface-formdata) and the WebKit implementation just got merged, Chromium and Gecko should be close behind 🤞 

I'll change this PR to a lighter weight approach (e.g. fall back to adding the entry explicitly, or use [this polyfill](https://github.com/jenseng/formdata-submitter-polyfill)), but I'll need to get jsdom updated (again 😆 ) before I do that. So between getting jest and jsdom updated, this PR is kind of in a holding pattern, so I'll switch it to a draft in the meantime.

2023-02-01 15:06 UTC, brophdawg11 commented
@jenseng oh dang, nice work!  Would you mind re-assigning me when things get moving again here to get it on my radar?

2023-04-18 21:59 UTC, jenseng commented
I've been in a slight holding pattern with jest and jsdom. Once a new version of jsdom is released with [this fix](https://github.com/jsdom/jsdom/pull/3514), jest [will be able to upgrade](https://github.com/facebook/jest/pull/13825) to the latest jsdom, which includes other fixes that will let us remove the various polyfills.

I also have a PR to add [submitter support to jsdom](https://github.com/jsdom/jsdom/pull/3496), though we could potentially move along without that, if we're open to idea of robustly polyfilling it for old browsers and jsdom ... see https://github.com/jenseng/formdata-submitter-polyfill

2023-05-06 20:35 UTC, jenseng commented
I've got an update just about ready for this PR, just want to get #10453 merged first as it will simplify stuff a bit :)

2023-05-25 23:38 UTC, jenseng commented
Ok @brophdawg11, this should be good to go 🤞 ... I don't have permission to assign issues, so pinging you yet again 🙂

I tried to keep the change as minimal as possible, though I still had to bump up the package sizes a tad

2023-05-25 23:41 UTC, jenseng commented on package.json
> +    "@typescript/lib-dom": "npm:@types/web",
typescript 4.8 ships with an older dom lib, this gets us on the latest so that TS knows about the submitter

2023-05-26 16:28 UTC, jenseng commented on packages/react-router-dom/__tests__/data-browser-router-legacy-formdata-test.tsx
> +// // needs to be done before remix is required, since it does some FormData
s/remix/react-router-dom/

2023-05-26 16:36 UTC, jenseng commented
Two slight variations we could consider:

1. Keep the PR mostly as-is, but don't bother with the image button logic. Then it works essentially the same as before if you're on old browser. If people want 100% correct submitter behavior for old browsers, they can use a polyfill.
2. Use [the polyfill](https://github.com/jenseng/formdata-submitter-polyfill) in this PR (for the implementation, not just tests). This would simplify the code, reduce the bundle size, and make the tests redundant, but then react-router-dom would have a third-party dependency

2023-05-27 17:45 UTC, jenseng commented
New `jsdom` just landed w/ submitter support, so I just pushed a commit to simplify tests a tiny bit

2023-06-06 21:21 UTC, brophdawg11 commented
Thanks @jenseng!  I inlined the `buildFormData` method since it only applies to the button/image fork currently.  Going to look into upgrading to Ts 5 against `dev` and hopefully remove the need to hijack the `lib-dom` types

2023-06-06 21:31 UTC, jenseng commented on package.json
> +    "@typescript/lib-dom": "npm:@types/web",
Looks like none of the 5.0.x releases have it, but it's included in 5.1.3

2023-06-06 23:10 UTC, MichaelDeBoey approved these changes

2023-06-09 23:21 UTC, jenseng commented
@brophdawg11 here's a [PR to upgrade to the latest typescript](https://github.com/remix-run/react-router/pull/10581)

2023-06-14 21:08 UTC, brophdawg11 approved these changes

2023-06-14 21:16 UTC, merged

2023-06-14 21:16 UTC, brophdawg11 commented
🥳 Thanks for all the work that led to this @jenseng!